services:
  - type: web
    name: historia
    env: docker
    plan: free
    region: singapore
    branch: main
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: historia-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
  - type: web
    name: historia-staging
    env: docker
    plan: free
    region: singapore
    branch: main
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: historia-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        fromService:
          type: web
          name: historia
          envVarKey: RAILS_MASTER_KEY

databases:
  - name: historia-db
    plan: free
    region: singapore
