previews: true

services:
  - type: web
    name: historia
    env: ruby
    plan: free
    branch: main
    autoDeploy: false
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: historia-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

  - type: web
    name: historia-staging
    env: ruby
    plan: free
    branch: main
    autoDeploy: true
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: historia-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        fromService:
          type: web
          name: historia
          envVarKey: RAILS_MASTER_KEY

  - type: psql
    name: historia-db
